config/routes.rb
Rails.application.routes.draw do
  resources :crewmembers


  root 'crewmembers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crewmember.rb
class Crewmember < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crewmembers_controller.rb
class CrewmembersController < ApplicationController
  before_action :set_crewmember, only: [:show, :edit, :update, :destroy]

  # GET /crewmembers
  # GET /crewmembers.json
  def index
    @crewmembers = Crewmember.all
  end

  # GET /crewmembers/1
  # GET /crewmembers/1.json
  def show
  end

  # GET /crewmembers/new
  def new
    @crewmember = Crewmember.new
  end

  # GET /crewmembers/1/edit
  def edit
  end

  # POST /crewmembers
  # POST /crewmembers.json
  def create
    @crewmember = Crewmember.new(crewmember_params)

    respond_to do |format|
      if @crewmember.save
        format.html { redirect_to @crewmember, notice: 'Crewmember was successfully created.' }
        format.json { render :show, status: :created, location: @crewmember }
      else
        format.html { render :new }
        format.json { render json: @crewmember.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crewmembers/1
  # PATCH/PUT /crewmembers/1.json
  def update
    respond_to do |format|
      if @crewmember.update(crewmember_params)
        format.html { redirect_to @crewmember, notice: 'Crewmember was successfully updated.' }
        format.json { render :show, status: :ok, location: @crewmember }
      else
        format.html { render :edit }
        format.json { render json: @crewmember.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crewmembers/1
  # DELETE /crewmembers/1.json
  def destroy
    @crewmember.destroy
    respond_to do |format|
      format.html { redirect_to crewmembers_url, notice: 'Crewmember was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crewmember
      @crewmember = Crewmember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crewmember_params
      params.require(:crewmember).permit(:name, :address, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crewmembers_helper.rb
module CrewmembersHelper
end

app/views/crewmembers/_form.html.erb
<%= form_with(model: crewmember, local: true) do |form| %>
  <% if crewmember.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crewmember.errors.count, "error") %> prohibited this crewmember from being saved:</h2>

      <ul>
      <% crewmember.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crewmembers/edit.html.erb
<h1>Editing Crewmember</h1>

<%= render 'form', crewmember: @crewmember %>

<%= link_to 'Show', @crewmember %> |
<%= link_to 'Back', crewmembers_path %>

app/views/crewmembers/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Crewmembers</h1>
<div class="place">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crewmembers.each do |crewmember| %>
      <tr>
        <td><%= crewmember.name %></td>
        <td><%= crewmember.address %></td>
        <td><%= crewmember.phone %></td>
        <td><%= crewmember.email %></td>
        <td><%= link_to 'Show', crewmember %></td>
        <td><%= link_to 'Edit', edit_crewmember_path(crewmember) %></td>
        <td><%= link_to 'Destroy', crewmember, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crewmember', new_crewmember_path %>
</div>

app/views/crewmembers/new.html.erb
<h1>New Crewmember</h1>

<%= render 'form', crewmember: @crewmember %>

<%= link_to 'Back', crewmembers_path %>

app/views/crewmembers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crewmember.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @crewmember.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @crewmember.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @crewmember.email %>
</p>

<%= link_to 'Edit', edit_crewmember_path(@crewmember) %> |
<%= link_to 'Back', crewmembers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crewof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=  javascript_include_tag 'application', 'data-turbolinks-track': "false"
    %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>